#!/usr/bin/env python3
"""Generate src/unifi/catalog.lua from the UniFi Network application's
own model registry.

    python3 tools/uidb-catalog.py --uidb uidb.json --bundles bundles.json [--fw] \
        > src/unifi/catalog.lua

uidb.json and bundles.json ship inside the Network application package
(unifi_sysvinit_all.deb: usr/lib/unifi/dl/uidb/uidb.json and
usr/lib/unifi/dl/firmware/bundles.json). --fw adds each platform's current
release version from fw-update.ui.com: the controller calls a device
"upgradable" whenever its reported version differs from that string, so an
identity without it shows a permanent Upgrade badge until the first upgrade
round teaches openUF the right one (upgrade.lua).

Only access points (unifi.network.type == "uap") that the controller adopts
are kept, reduced to what unifi/identity.lua matches on and what an identity
needs.
"""

import argparse
import json
import sys
import urllib.request

FW_URL = ("https://fw-update.ui.com/api/firmware-latest?filter=eq~~product~~unifi-firmware"
          "&filter=eq~~channel~~release&limit=1000")


def gen_of(features, sku="", chipset=""):
    f = features or {}
    # Several WiFi 7 entries (U7-LR, U7-IW, U7-Mesh) carry no `be` flag; the
    # SKU family and the WiFi 7 chipset code say it instead.
    if f.get("be") or sku.startswith(("U7-", "E7")) or chipset == "r":
        return "be"
    if f.get("ax"):
        return "ax"
    if f.get("ac"):
        return "ac"
    return "n"


def fw_versions():
    with urllib.request.urlopen(FW_URL, timeout=30) as r:
        data = json.load(r)
    out = {}
    for f in data.get("_embedded", {}).get("firmware", []):
        v = f.get("version") or ""
        # "v6.8.2+15592" -> "6.8.2.15592", the bare form the inform carries.
        v = v.lstrip("v").replace("+", ".")
        if f.get("platform") and v:
            out[f["platform"]] = v
    return out


def lua_str(s):
    return '"' + str(s).replace("\\", "\\\\").replace('"', '\\"') + '"'


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--uidb", required=True)
    ap.add_argument("--bundles", required=True)
    ap.add_argument("--fw", action="store_true", help="add current firmware versions")
    a = ap.parse_args()

    uidb = json.load(open(a.uidb))
    bundles = json.load(open(a.bundles))
    fw = fw_versions() if a.fw else {}

    rows = []
    for d in uidb["devices"]:
        n = d.get("unifi", {}).get("network", {})
        if n.get("type") != "uap":
            continue
        if d.get("unifi", {}).get("adoptability", "adoptable") != "adoptable":
            continue
        radios = n.get("radios") or {}
        bands = sorted(b for b in radios if b in ("ng", "na", "6e"))
        if not bands:
            continue
        model = n["model"]
        name = (d.get("product") or {}).get("name") or model
        platform = (bundles.get(model) or {}).get("base_model") or model
        caps = n.get("deviceCapabilities") or []
        forms = n.get("formFactor") or []
        rows.append({
            "model": model,
            "sku": d.get("sku") or "",
            "name": name,
            "sysid": int(n.get("systemIdHexadecimal") or d.get("sysid") or "0", 16),
            "platform": platform,
            "bands": bands,
            "gen": gen_of(n.get("features"), d.get("sku") or "", n.get("chipset") or ""),
            "ports": int(n.get("numberOfPorts") or 1),
            "switch": "ACCESS_POINT_SWITCH" in caps,
            # uidb has no outdoor flag: a pole mount or the product name says it.
            "outdoor": "POLE" in forms or "outdoor" in name.lower(),
            "mesh": "mesh" in name.lower() or "extender" in name.lower(),
            "speed": {b: int((radios.get(b) or {}).get("maxSpeedMegabitsPerSecond") or 0) for b in bands},
            "fw": fw.get(model) or fw.get(platform) or "",
        })
    rows.sort(key=lambda r: r["model"])

    w = sys.stdout.write
    w("-- Generated by tools/uidb-catalog.py from the UniFi Network application's\n")
    w("-- model registry (uidb %s). Do not edit by hand; regenerate.\n" % uidb.get("version", "?"))
    w("return {\n")
    w("\tuidb = %s,\n" % lua_str(uidb.get("version", "")))
    w("\tmodels = {\n")
    for r in rows:
        speed = ", ".join('["%s"] = %d' % (b, r["speed"][b]) for b in r["bands"])
        w("\t\t{model = %s, sku = %s, name = %s, sysid = 0x%04x, platform = %s,\n"
          % (lua_str(r["model"]), lua_str(r["sku"]), lua_str(r["name"]), r["sysid"], lua_str(r["platform"])))
        w("\t\t bands = {%s}, gen = %s, ports = %d, switch = %s, outdoor = %s, mesh = %s,\n"
          % (", ".join(lua_str(b) for b in r["bands"]), lua_str(r["gen"]), r["ports"],
             "true" if r["switch"] else "false", "true" if r["outdoor"] else "false",
             "true" if r["mesh"] else "false"))
        w("\t\t speed = {%s}, fw = %s},\n" % (speed, lua_str(r["fw"])))
    w("\t},\n")
    w("}\n")


if __name__ == "__main__":
    main()
