--[[
	identity.lua -- which UniFi access point this device presents itself as.

	The candidates are the controller's own model registry (catalog.lua,
	generated by tools/uidb-catalog.py); modelmatch.lua scores them against
	the facts of a board (its bands, PHY generation, spatial streams,
	channel width, socket count). A choice once made is kept: an adopted
	device must never change model under the controller, so the caller
	persists the model code and hands it back as `saved`.

	Pure: the caller supplies the board (OpenWrt's board.json, decoded) and
	stores the result.
]]--

local match = require("unifi.modelmatch")

local M = {}

-- When the board describes nothing to match on: the model openUF was first
-- validated as.
M.FALLBACK = "U6IW"

M._catalog = function() return require("unifi.catalog") end

-- The identity table (inform/announce fields: model, sysid, fw, port layout)
-- plus the chosen model code, whether this was a fresh choice, and its score.
---@param board table?   /etc/board.json, decoded
---@param saved string?  the model code chosen before
---@return Identity identity
---@return string code
---@return boolean fresh
---@return number? score
function M.choose(board, saved)
	local catalog = M._catalog()
	local chosen = saved and match.find(catalog, saved) or nil
	local fresh, score = false, nil
	if not chosen and type(board) == "table" then
		local facts = match.facts(board)
		if facts then
			chosen, score = match.best(catalog, facts)
			fresh = chosen ~= nil
		end
	end
	if not chosen then chosen = match.find(catalog, M.FALLBACK) end
	return match.identity(chosen), chosen.model, fresh, score
end

-- The registry version the catalogue was generated from, for the record.
function M.uidb()
	return M._catalog().uidb
end

return M
