--[[
	Hardware profile derived from the board itself, for DSA boards that have
	no hand-written map. Reads OpenWrt's own /etc/board.json (generated by
	board.d from the device tree), the running bridge and /sys/class/leds, and
	settles on:

	  • sockets     network.wan.device + network.lan.ports (or lan.device on a
	                single-port board), in that order
	  • uplink      the socket the default gateway's MAC is learned on (bridge
	                FDB), else board.json's wan device, else the first socket
	  • identity    the closest UniFi AP (ufmodel/auto.lua: modelmatch.lua
	                against the controller's own model registry)
	  • numbering   that model's registry order: a model with a built-in
	                switch takes its uplink on the LAST port (U6IW: port 5,
	                "PoE In + Data") and the others from 1 in socket order; a
	                plain AP takes it on port 1 -- the controller stores
	                per-port settings against these numbers
	  • MAC         the MAC the network already knows this AP by: the bridge
	                the uplink sits in, else board.json's label MAC. NOT the
	                uplink socket's own MAC, which on some boards (a Netgear
	                WAX220's eth0) is random on every boot
	  • LED         the first of status/power/system/run, preferring blue,
	                white, green
	  • radios      every wifi-device in /etc/config/wireless

	The result is written to /etc/openuf/modelmap-auto.json once the uplink
	could actually be DETECTED, and read back from there on every later start:
	numbering and identity must not move under an adopted device just because
	someone moved a cable. Delete that file to re-derive.

	Swconfig boards are not covered (their sockets are not netdevs); use a
	board-specific map there.
]]--

local STATE_FILE = "/etc/openuf/modelmap-auto.json"

local ok_json, cjson = pcall(require, "cjson")

local function read(path)
	local f = io.open(path, "r")
	if not f then return nil end
	local s = f:read("*a")
	f:close()
	return s
end

local function decode(s)
	if not (ok_json and s and s ~= "") then return nil end
	local ok, t = pcall(cjson.decode, s)
	return ok and type(t) == "table" and t or nil
end

local function sh(cmd)
	local h = io.popen(cmd .. " 2>/dev/null")
	if not h then return "" end
	local s = h:read("*a") or ""
	h:close()
	return s
end

local function mac_of(ifname)
	local m = (read("/sys/class/net/" .. ifname .. "/address") or ""):match("(%x%x:%x%x:%x%x:%x%x:%x%x:%x%x)")
	return m and m:lower() or nil
end

local function master_of(ifname)
	local m = sh("readlink /sys/class/net/" .. ifname .. "/master"):match("([^/%s]+)%s*$")
	return (m and m ~= "") and m or nil
end

local function sibling(rel)
	for _, p in ipairs({rel, "openuf/" .. rel, "/opt/openuf/" .. rel}) do
		local f = io.open(p, "r")
		if f then f:close(); return dofile(p) end
	end
	return nil
end

-- The chosen identity (ufmodel/auto.lua persists it), for its port layout.
local ok_id, identity = pcall(sibling, "ufmodel/auto.lua")
if not ok_id or type(identity) ~= "table" then identity = {} end

local function derive()
	local board = decode(read("/etc/board.json")) or {}
	local net = board.network or {}

	local sockets, seen = {}, {}
	local function add(i)
		if type(i) == "string" and i ~= "" and not seen[i] then
			seen[i] = true
			sockets[#sockets + 1] = i
		end
	end
	if net.wan then add(net.wan.device) end
	if net.lan then
		for _, p in ipairs(net.lan.ports or {}) do add(p) end
		add(net.lan.device)
	end
	if #sockets == 0 then add("eth0") end

	-- The gateway's MAC, then the socket it was learned on.
	local uplink, detected = nil, false
	local gw_ip = sh("ip -4 route show default"):match("via%s+(%d+%.%d+%.%d+%.%d+)")
	local gw_mac = gw_ip and (read("/proc/net/arp") or ""):match(
		gw_ip:gsub("%.", "%%.") .. "%s+%S+%s+%S+%s+(%x%x:%x%x:%x%x:%x%x:%x%x:%x%x)")
	if gw_mac then
		for line in sh("bridge fdb show"):gmatch("[^\n]+") do
			local mac, dev = line:match("^(%x%x:%x%x:%x%x:%x%x:%x%x:%x%x)%s+dev%s+(%S+)")
			if mac and mac:lower() == gw_mac:lower() and seen[dev] and line:find("master") then
				uplink, detected = dev, true
				break
			end
		end
	end
	if not uplink then uplink = (net.wan and net.wan.device) or sockets[1] end
	-- A board whose one socket IS the uplink needs no detection to be sure.
	if #sockets == 1 then detected = true end

	-- The uplink's port number comes from the model's registry layout; the
	-- other sockets fill the remaining numbers in order.
	local up_idx = tonumber(identity.uplink_idx) or 5
	local ports, idx = {}, 1
	for _, s in ipairs(sockets) do
		if s ~= uplink then
			if idx == up_idx then idx = idx + 1 end
			ports[#ports + 1] = {idx = idx, ifname = s}
			idx = idx + 1
		end
	end
	ports[#ports + 1] = {idx = up_idx, ifname = uplink}

	local br = master_of(uplink)
	local identity = (br and mac_of(br))
		or (board.system and board.system.label_macaddr)
		or (net.lan and net.lan.macaddr)
		or mac_of(uplink)

	local leds = {}
	for name in sh("ls /sys/class/leds"):gmatch("%S+") do leds[#leds + 1] = name end
	local led
	for _, fn in ipairs({"status", "power", "system", "run"}) do
		for _, colour in ipairs({"blue", "white", "green", ""}) do
			for _, n in ipairs(leds) do
				if not led and n:find(fn, 1, true) and n:find(colour, 1, true) then led = n end
			end
		end
	end

	local radios = {}
	for name in sh("uci -q show wireless"):gmatch("wireless%.([%w_]+)=wifi%-device") do
		radios[#radios + 1] = name
	end
	if #radios == 0 then radios = {"radio0", "radio1"} end

	return {
		ports = ports, uplink = uplink, identity_mac = identity and identity:lower(),
		led = led, radios = radios,
	}, detected
end

local saved = decode(read(STATE_FILE))
if not (saved and saved.ports and saved.uplink) then
	local fresh, detected = derive()
	saved = fresh
	if detected and ok_json then
		local f = io.open(STATE_FILE, "w")
		if f then
			f:write(cjson.encode(fresh))
			f:close()
		end
	end
end

local dev = {}
dev.conf = {}
dev.conf.net = {
	lan_name     = "lan",
	lan_cpueth   = saved.uplink,
	lan_vlanid   = 1,
	wan_cpueth   = saved.uplink,
	identity_mac = saved.identity_mac,
	ports        = {},
}
for _, p in ipairs(saved.ports) do
	dev.conf.net.ports[#dev.conf.net.ports + 1] = {idx = p.idx, ifname = p.ifname}
end
dev.conf.led = saved.led
dev.openuf = {}
dev.openuf.uap = {
	ufmodel  = identity.model and "auto" or "u6iw",
	hwassign = saved.radios,
}

return dev
